# Git aliases
alias g='git status'
alias gs='git status'
alias gl='git log'
alias ga='git add'
alias gaa='git add .'
alias gco='git checkout'
alias gb='git branch'
alias gc='git commit'
alias gd='git diff'
alias gds='git diff --staged'
